; Jalekon Compiler Output
; Generated by jalekon_compiler.py
; Program: def add(a, b): return a + b; print(add(3, 4))

@.fmt_int = private unnamed_addr constant [4 x i8] c"%d\0A\00"
declare i32 @printf(ptr, ...)

define i64 @add(i64 %a, i64 %b) {
entry:
  %t1 = alloca i64
  store i64 %a, ptr %t1
  %t2 = alloca i64
  store i64 %b, ptr %t2
  %t3 = load i64, ptr %t1
  %t4 = load i64, ptr %t2
  %t5 = add i64 %t3, %t4
  ret i64 %t5
}

define i32 @main() {
entry:
  %t1 = call i64 @add(i64 3, i64 4)
  %t2 = call i32 (ptr, ...) @printf(ptr @.fmt_int, i64 %t1)
  ret i32 0
}
